version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - '3000:3000'
    environment:
      - CLIENT_URL=http://localhost:5173
      - MONGODB_URI=mongodb://mongodb:27017/githubProfile
#     - GITHUB_CLIENT_ID=
#     - GITHUB_CLIENT_SECRET=

    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  mongo_data:
